DROP TABLE IF EXISTS order_product;
DROP TABLE IF EXISTS orderr;
DROP TABLE IF EXISTS payment;
DROP TABLE IF EXISTS product_category;
DROP TABLE IF EXISTS product_stock;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS USER;